/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/app.activity'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppBusinessRouteImport } from './routes/_authenticated/app.business'
import { Route as AuthenticatedAppModulesRouteImport } from './routes/_authenticated/app.modules'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as SuperAdminAppIndexRouteImport } from './routes/super-admin._app.index'
import { Route as SuperAdminAppBriefRouteImport } from './routes/super-admin._app.brief'
import { Route as SuperAdminAppRevenueRouteImport } from './routes/super-admin._app.revenue'
import { Route as SuperAdminAppSubscriptionsRouteImport } from './routes/super-admin._app.subscriptions'
import { Route as AuthenticatedAppAutomotiveIndexRouteImport } from './routes/_authenticated/app/automotive/index'
import { Route as AuthenticatedAppAutomotiveCustomersRouteImport } from './routes/_authenticated/app/automotive/customers'
import { Route as AuthenticatedAppAutomotiveReportsRouteImport } from './routes/_authenticated/app/automotive/reports'
import { Route as AuthenticatedAppAutomotiveReservationsRouteImport } from './routes/_authenticated/app/automotive/reservations'
import { Route as AuthenticatedAppAutomotiveSalesRouteImport } from './routes/_authenticated/app/automotive/sales'
import { Route as AuthenticatedAppAutomotiveVehiclesRouteImport } from './routes/_authenticated/app/automotive/vehicles'
import { Route as AuthenticatedAppAutomotiveVehiclesIdRouteImport } from './routes/_authenticated/app/automotive/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBusinessRoute =
  AuthenticatedAppBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModulesRoute = AuthenticatedAppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const SuperAdminAppIndexRoute = SuperAdminAppIndexRouteImport.update({
  id: '/super-admin/_app/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAppBriefRoute = SuperAdminAppBriefRouteImport.update({
  id: '/super-admin/_app/brief',
  path: '/super-admin/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAppRevenueRoute = SuperAdminAppRevenueRouteImport.update({
  id: '/super-admin/_app/revenue',
  path: '/super-admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAppSubscriptionsRoute =
  SuperAdminAppSubscriptionsRouteImport.update({
    id: '/super-admin/_app/subscriptions',
    path: '/super-admin/subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAutomotiveIndexRoute =
  AuthenticatedAppAutomotiveIndexRouteImport.update({
    id: '/automotive/',
    path: '/automotive/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveCustomersRoute =
  AuthenticatedAppAutomotiveCustomersRouteImport.update({
    id: '/automotive/customers',
    path: '/automotive/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveReportsRoute =
  AuthenticatedAppAutomotiveReportsRouteImport.update({
    id: '/automotive/reports',
    path: '/automotive/reports',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveReservationsRoute =
  AuthenticatedAppAutomotiveReservationsRouteImport.update({
    id: '/automotive/reservations',
    path: '/automotive/reservations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveSalesRoute =
  AuthenticatedAppAutomotiveSalesRouteImport.update({
    id: '/automotive/sales',
    path: '/automotive/sales',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveVehiclesRoute =
  AuthenticatedAppAutomotiveVehiclesRouteImport.update({
    id: '/automotive/vehicles',
    path: '/automotive/vehicles',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveVehiclesIdRoute =
  AuthenticatedAppAutomotiveVehiclesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAutomotiveVehiclesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business': typeof AuthenticatedAppBusinessRoute
  '/app/modules': typeof AuthenticatedAppModulesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/super-admin/brief': typeof SuperAdminAppBriefRoute
  '/super-admin/revenue': typeof SuperAdminAppRevenueRoute
  '/super-admin/subscriptions': typeof SuperAdminAppSubscriptionsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/super-admin/': typeof SuperAdminAppIndexRoute
  '/app/automotive/customers': typeof AuthenticatedAppAutomotiveCustomersRoute
  '/app/automotive/reports': typeof AuthenticatedAppAutomotiveReportsRoute
  '/app/automotive/reservations': typeof AuthenticatedAppAutomotiveReservationsRoute
  '/app/automotive/sales': typeof AuthenticatedAppAutomotiveSalesRoute
  '/app/automotive/vehicles': typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  '/app/automotive/': typeof AuthenticatedAppAutomotiveIndexRoute
  '/app/automotive/vehicles/$id': typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business': typeof AuthenticatedAppBusinessRoute
  '/app/modules': typeof AuthenticatedAppModulesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/super-admin/brief': typeof SuperAdminAppBriefRoute
  '/super-admin/revenue': typeof SuperAdminAppRevenueRoute
  '/super-admin/subscriptions': typeof SuperAdminAppSubscriptionsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/super-admin': typeof SuperAdminAppIndexRoute
  '/app/automotive/customers': typeof AuthenticatedAppAutomotiveCustomersRoute
  '/app/automotive/reports': typeof AuthenticatedAppAutomotiveReportsRoute
  '/app/automotive/reservations': typeof AuthenticatedAppAutomotiveReservationsRoute
  '/app/automotive/sales': typeof AuthenticatedAppAutomotiveSalesRoute
  '/app/automotive/vehicles': typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  '/app/automotive': typeof AuthenticatedAppAutomotiveIndexRoute
  '/app/automotive/vehicles/$id': typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/business': typeof AuthenticatedAppBusinessRoute
  '/_authenticated/app/modules': typeof AuthenticatedAppModulesRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/super-admin/_app/brief': typeof SuperAdminAppBriefRoute
  '/super-admin/_app/revenue': typeof SuperAdminAppRevenueRoute
  '/super-admin/_app/subscriptions': typeof SuperAdminAppSubscriptionsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/super-admin/_app/': typeof SuperAdminAppIndexRoute
  '/_authenticated/app/automotive/customers': typeof AuthenticatedAppAutomotiveCustomersRoute
  '/_authenticated/app/automotive/reports': typeof AuthenticatedAppAutomotiveReportsRoute
  '/_authenticated/app/automotive/reservations': typeof AuthenticatedAppAutomotiveReservationsRoute
  '/_authenticated/app/automotive/sales': typeof AuthenticatedAppAutomotiveSalesRoute
  '/_authenticated/app/automotive/vehicles': typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  '/_authenticated/app/automotive/': typeof AuthenticatedAppAutomotiveIndexRoute
  '/_authenticated/app/automotive/vehicles/$id': typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/register'
    | '/app'
    | '/app/activity'
    | '/app/billing'
    | '/app/business'
    | '/app/modules'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/team'
    | '/super-admin/brief'
    | '/super-admin/revenue'
    | '/super-admin/subscriptions'
    | '/app/'
    | '/super-admin/'
    | '/app/automotive/customers'
    | '/app/automotive/reports'
    | '/app/automotive/reservations'
    | '/app/automotive/sales'
    | '/app/automotive/vehicles'
    | '/app/automotive/'
    | '/app/automotive/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/register'
    | '/app/activity'
    | '/app/billing'
    | '/app/business'
    | '/app/modules'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/team'
    | '/super-admin/brief'
    | '/super-admin/revenue'
    | '/super-admin/subscriptions'
    | '/app'
    | '/super-admin'
    | '/app/automotive/customers'
    | '/app/automotive/reports'
    | '/app/automotive/reservations'
    | '/app/automotive/sales'
    | '/app/automotive/vehicles'
    | '/app/automotive'
    | '/app/automotive/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/login'
    | '/register'
    | '/_authenticated/app'
    | '/_authenticated/app/activity'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/business'
    | '/_authenticated/app/modules'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/team'
    | '/super-admin/_app/brief'
    | '/super-admin/_app/revenue'
    | '/super-admin/_app/subscriptions'
    | '/_authenticated/app/'
    | '/super-admin/_app/'
    | '/_authenticated/app/automotive/customers'
    | '/_authenticated/app/automotive/reports'
    | '/_authenticated/app/automotive/reservations'
    | '/_authenticated/app/automotive/sales'
    | '/_authenticated/app/automotive/vehicles'
    | '/_authenticated/app/automotive/'
    | '/_authenticated/app/automotive/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SuperAdminAppBriefRoute: typeof SuperAdminAppBriefRoute
  SuperAdminAppRevenueRoute: typeof SuperAdminAppRevenueRoute
  SuperAdminAppSubscriptionsRoute: typeof SuperAdminAppSubscriptionsRoute
  SuperAdminAppIndexRoute: typeof SuperAdminAppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activity': {
      id: '/_authenticated/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/business': {
      id: '/_authenticated/app/business'
      path: '/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AuthenticatedAppBusinessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/modules': {
      id: '/_authenticated/app/modules'
      path: '/modules'
      fullPath: '/app/modules'
      preLoaderRoute: typeof AuthenticatedAppModulesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/super-admin/_app/': {
      id: '/super-admin/_app/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminAppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_app/brief': {
      id: '/super-admin/_app/brief'
      path: '/super-admin/brief'
      fullPath: '/super-admin/brief'
      preLoaderRoute: typeof SuperAdminAppBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_app/revenue': {
      id: '/super-admin/_app/revenue'
      path: '/super-admin/revenue'
      fullPath: '/super-admin/revenue'
      preLoaderRoute: typeof SuperAdminAppRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/_app/subscriptions': {
      id: '/super-admin/_app/subscriptions'
      path: '/super-admin/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof SuperAdminAppSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/automotive/': {
      id: '/_authenticated/app/automotive/'
      path: '/automotive'
      fullPath: '/app/automotive/'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/customers': {
      id: '/_authenticated/app/automotive/customers'
      path: '/automotive/customers'
      fullPath: '/app/automotive/customers'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/reports': {
      id: '/_authenticated/app/automotive/reports'
      path: '/automotive/reports'
      fullPath: '/app/automotive/reports'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/reservations': {
      id: '/_authenticated/app/automotive/reservations'
      path: '/automotive/reservations'
      fullPath: '/app/automotive/reservations'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveReservationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/sales': {
      id: '/_authenticated/app/automotive/sales'
      path: '/automotive/sales'
      fullPath: '/app/automotive/sales'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/vehicles': {
      id: '/_authenticated/app/automotive/vehicles'
      path: '/automotive/vehicles'
      fullPath: '/app/automotive/vehicles'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveVehiclesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/vehicles/$id': {
      id: '/_authenticated/app/automotive/vehicles/$id'
      path: '/$id'
      fullPath: '/app/automotive/vehicles/$id'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedAppAutomotiveVehiclesRoute
    }
  }
}

interface AuthenticatedAppAutomotiveVehiclesRouteChildren {
  AuthenticatedAppAutomotiveVehiclesIdRoute: typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}

const AuthenticatedAppAutomotiveVehiclesRouteChildren: AuthenticatedAppAutomotiveVehiclesRouteChildren =
  {
    AuthenticatedAppAutomotiveVehiclesIdRoute:
      AuthenticatedAppAutomotiveVehiclesIdRoute,
  }

const AuthenticatedAppAutomotiveVehiclesRouteWithChildren =
  AuthenticatedAppAutomotiveVehiclesRoute._addFileChildren(
    AuthenticatedAppAutomotiveVehiclesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppBusinessRoute: typeof AuthenticatedAppBusinessRoute
  AuthenticatedAppModulesRoute: typeof AuthenticatedAppModulesRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAutomotiveCustomersRoute: typeof AuthenticatedAppAutomotiveCustomersRoute
  AuthenticatedAppAutomotiveReportsRoute: typeof AuthenticatedAppAutomotiveReportsRoute
  AuthenticatedAppAutomotiveReservationsRoute: typeof AuthenticatedAppAutomotiveReservationsRoute
  AuthenticatedAppAutomotiveSalesRoute: typeof AuthenticatedAppAutomotiveSalesRoute
  AuthenticatedAppAutomotiveVehiclesRoute: typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  AuthenticatedAppAutomotiveIndexRoute: typeof AuthenticatedAppAutomotiveIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppBusinessRoute: AuthenticatedAppBusinessRoute,
  AuthenticatedAppModulesRoute: AuthenticatedAppModulesRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAutomotiveCustomersRoute:
    AuthenticatedAppAutomotiveCustomersRoute,
  AuthenticatedAppAutomotiveReportsRoute:
    AuthenticatedAppAutomotiveReportsRoute,
  AuthenticatedAppAutomotiveReservationsRoute:
    AuthenticatedAppAutomotiveReservationsRoute,
  AuthenticatedAppAutomotiveSalesRoute: AuthenticatedAppAutomotiveSalesRoute,
  AuthenticatedAppAutomotiveVehiclesRoute:
    AuthenticatedAppAutomotiveVehiclesRouteWithChildren,
  AuthenticatedAppAutomotiveIndexRoute: AuthenticatedAppAutomotiveIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SuperAdminAppBriefRoute: SuperAdminAppBriefRoute,
  SuperAdminAppRevenueRoute: SuperAdminAppRevenueRoute,
  SuperAdminAppSubscriptionsRoute: SuperAdminAppSubscriptionsRoute,
  SuperAdminAppIndexRoute: SuperAdminAppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
