/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as SuperAdminAppRouteImport } from './routes/super-admin._app'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/app.activity'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppBusinessRouteImport } from './routes/_authenticated/app.business'
import { Route as AuthenticatedAppModulesRouteImport } from './routes/_authenticated/app.modules'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as SuperAdminAppIndexRouteImport } from './routes/super-admin._app.index'
import { Route as SuperAdminAppAccessRouteImport } from './routes/super-admin._app.access'
import { Route as SuperAdminAppAnnouncementsRouteImport } from './routes/super-admin._app.announcements'
import { Route as SuperAdminAppAuditLogsRouteImport } from './routes/super-admin._app.audit-logs'
import { Route as SuperAdminAppBriefRouteImport } from './routes/super-admin._app.brief'
import { Route as SuperAdminAppDatabaseRouteImport } from './routes/super-admin._app.database'
import { Route as SuperAdminAppEmployeesRouteImport } from './routes/super-admin._app.employees'
import { Route as SuperAdminAppFeatureFlagsRouteImport } from './routes/super-admin._app.feature-flags'
import { Route as SuperAdminAppNotificationsRouteImport } from './routes/super-admin._app.notifications'
import { Route as SuperAdminAppPaymentsRouteImport } from './routes/super-admin._app.payments'
import { Route as SuperAdminAppProfileRouteImport } from './routes/super-admin._app.profile'
import { Route as SuperAdminAppRevenueRouteImport } from './routes/super-admin._app.revenue'
import { Route as SuperAdminAppSettingsRouteImport } from './routes/super-admin._app.settings'
import { Route as SuperAdminAppStorageRouteImport } from './routes/super-admin._app.storage'
import { Route as SuperAdminAppSubscriptionsRouteImport } from './routes/super-admin._app.subscriptions'
import { Route as SuperAdminAppSupportRouteImport } from './routes/super-admin._app.support'
import { Route as SuperAdminAppSystemHealthRouteImport } from './routes/super-admin._app.system-health'
import { Route as SuperAdminAppTenantsRouteImport } from './routes/super-admin._app.tenants'
import { Route as AuthenticatedAppAutomotiveIndexRouteImport } from './routes/_authenticated/app/automotive/index'
import { Route as AuthenticatedAppAutomotiveCustomersRouteImport } from './routes/_authenticated/app/automotive/customers'
import { Route as AuthenticatedAppAutomotiveReportsRouteImport } from './routes/_authenticated/app/automotive/reports'
import { Route as AuthenticatedAppAutomotiveReservationsRouteImport } from './routes/_authenticated/app/automotive/reservations'
import { Route as AuthenticatedAppAutomotiveSalesRouteImport } from './routes/_authenticated/app/automotive/sales'
import { Route as AuthenticatedAppAutomotiveVehiclesRouteImport } from './routes/_authenticated/app/automotive/vehicles'
import { Route as AuthenticatedAppAutomotiveVehiclesIdRouteImport } from './routes/_authenticated/app/automotive/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SuperAdminAppRoute = SuperAdminAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperAdminRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBusinessRoute =
  AuthenticatedAppBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModulesRoute = AuthenticatedAppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const SuperAdminAppIndexRoute = SuperAdminAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppAccessRoute = SuperAdminAppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppAnnouncementsRoute =
  SuperAdminAppAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => SuperAdminAppRoute,
  } as any)
const SuperAdminAppAuditLogsRoute = SuperAdminAppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppBriefRoute = SuperAdminAppBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppDatabaseRoute = SuperAdminAppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppEmployeesRoute = SuperAdminAppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppFeatureFlagsRoute =
  SuperAdminAppFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => SuperAdminAppRoute,
  } as any)
const SuperAdminAppNotificationsRoute =
  SuperAdminAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SuperAdminAppRoute,
  } as any)
const SuperAdminAppPaymentsRoute = SuperAdminAppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppProfileRoute = SuperAdminAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppRevenueRoute = SuperAdminAppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppSettingsRoute = SuperAdminAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppStorageRoute = SuperAdminAppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppSubscriptionsRoute =
  SuperAdminAppSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => SuperAdminAppRoute,
  } as any)
const SuperAdminAppSupportRoute = SuperAdminAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const SuperAdminAppSystemHealthRoute =
  SuperAdminAppSystemHealthRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => SuperAdminAppRoute,
  } as any)
const SuperAdminAppTenantsRoute = SuperAdminAppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperAdminAppRoute,
} as any)
const AuthenticatedAppAutomotiveIndexRoute =
  AuthenticatedAppAutomotiveIndexRouteImport.update({
    id: '/automotive/',
    path: '/automotive/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveCustomersRoute =
  AuthenticatedAppAutomotiveCustomersRouteImport.update({
    id: '/automotive/customers',
    path: '/automotive/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveReportsRoute =
  AuthenticatedAppAutomotiveReportsRouteImport.update({
    id: '/automotive/reports',
    path: '/automotive/reports',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveReservationsRoute =
  AuthenticatedAppAutomotiveReservationsRouteImport.update({
    id: '/automotive/reservations',
    path: '/automotive/reservations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveSalesRoute =
  AuthenticatedAppAutomotiveSalesRouteImport.update({
    id: '/automotive/sales',
    path: '/automotive/sales',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveVehiclesRoute =
  AuthenticatedAppAutomotiveVehiclesRouteImport.update({
    id: '/automotive/vehicles',
    path: '/automotive/vehicles',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomotiveVehiclesIdRoute =
  AuthenticatedAppAutomotiveVehiclesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAutomotiveVehiclesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business': typeof AuthenticatedAppBusinessRoute
  '/app/modules': typeof AuthenticatedAppModulesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/super-admin/access': typeof SuperAdminAppAccessRoute
  '/super-admin/announcements': typeof SuperAdminAppAnnouncementsRoute
  '/super-admin/audit-logs': typeof SuperAdminAppAuditLogsRoute
  '/super-admin/brief': typeof SuperAdminAppBriefRoute
  '/super-admin/database': typeof SuperAdminAppDatabaseRoute
  '/super-admin/employees': typeof SuperAdminAppEmployeesRoute
  '/super-admin/feature-flags': typeof SuperAdminAppFeatureFlagsRoute
  '/super-admin/notifications': typeof SuperAdminAppNotificationsRoute
  '/super-admin/payments': typeof SuperAdminAppPaymentsRoute
  '/super-admin/profile': typeof SuperAdminAppProfileRoute
  '/super-admin/revenue': typeof SuperAdminAppRevenueRoute
  '/super-admin/settings': typeof SuperAdminAppSettingsRoute
  '/super-admin/storage': typeof SuperAdminAppStorageRoute
  '/super-admin/subscriptions': typeof SuperAdminAppSubscriptionsRoute
  '/super-admin/support': typeof SuperAdminAppSupportRoute
  '/super-admin/system-health': typeof SuperAdminAppSystemHealthRoute
  '/super-admin/tenants': typeof SuperAdminAppTenantsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/super-admin/': typeof SuperAdminAppIndexRoute
  '/app/automotive/customers': typeof AuthenticatedAppAutomotiveCustomersRoute
  '/app/automotive/reports': typeof AuthenticatedAppAutomotiveReportsRoute
  '/app/automotive/reservations': typeof AuthenticatedAppAutomotiveReservationsRoute
  '/app/automotive/sales': typeof AuthenticatedAppAutomotiveSalesRoute
  '/app/automotive/vehicles': typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  '/app/automotive/': typeof AuthenticatedAppAutomotiveIndexRoute
  '/app/automotive/vehicles/$id': typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/super-admin': typeof SuperAdminAppIndexRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business': typeof AuthenticatedAppBusinessRoute
  '/app/modules': typeof AuthenticatedAppModulesRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/super-admin/access': typeof SuperAdminAppAccessRoute
  '/super-admin/announcements': typeof SuperAdminAppAnnouncementsRoute
  '/super-admin/audit-logs': typeof SuperAdminAppAuditLogsRoute
  '/super-admin/brief': typeof SuperAdminAppBriefRoute
  '/super-admin/database': typeof SuperAdminAppDatabaseRoute
  '/super-admin/employees': typeof SuperAdminAppEmployeesRoute
  '/super-admin/feature-flags': typeof SuperAdminAppFeatureFlagsRoute
  '/super-admin/notifications': typeof SuperAdminAppNotificationsRoute
  '/super-admin/payments': typeof SuperAdminAppPaymentsRoute
  '/super-admin/profile': typeof SuperAdminAppProfileRoute
  '/super-admin/revenue': typeof SuperAdminAppRevenueRoute
  '/super-admin/settings': typeof SuperAdminAppSettingsRoute
  '/super-admin/storage': typeof SuperAdminAppStorageRoute
  '/super-admin/subscriptions': typeof SuperAdminAppSubscriptionsRoute
  '/super-admin/support': typeof SuperAdminAppSupportRoute
  '/super-admin/system-health': typeof SuperAdminAppSystemHealthRoute
  '/super-admin/tenants': typeof SuperAdminAppTenantsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/automotive/customers': typeof AuthenticatedAppAutomotiveCustomersRoute
  '/app/automotive/reports': typeof AuthenticatedAppAutomotiveReportsRoute
  '/app/automotive/reservations': typeof AuthenticatedAppAutomotiveReservationsRoute
  '/app/automotive/sales': typeof AuthenticatedAppAutomotiveSalesRoute
  '/app/automotive/vehicles': typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  '/app/automotive': typeof AuthenticatedAppAutomotiveIndexRoute
  '/app/automotive/vehicles/$id': typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/super-admin/_app': typeof SuperAdminAppRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/_authenticated/app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/business': typeof AuthenticatedAppBusinessRoute
  '/_authenticated/app/modules': typeof AuthenticatedAppModulesRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/super-admin/_app/access': typeof SuperAdminAppAccessRoute
  '/super-admin/_app/announcements': typeof SuperAdminAppAnnouncementsRoute
  '/super-admin/_app/audit-logs': typeof SuperAdminAppAuditLogsRoute
  '/super-admin/_app/brief': typeof SuperAdminAppBriefRoute
  '/super-admin/_app/database': typeof SuperAdminAppDatabaseRoute
  '/super-admin/_app/employees': typeof SuperAdminAppEmployeesRoute
  '/super-admin/_app/feature-flags': typeof SuperAdminAppFeatureFlagsRoute
  '/super-admin/_app/notifications': typeof SuperAdminAppNotificationsRoute
  '/super-admin/_app/payments': typeof SuperAdminAppPaymentsRoute
  '/super-admin/_app/profile': typeof SuperAdminAppProfileRoute
  '/super-admin/_app/revenue': typeof SuperAdminAppRevenueRoute
  '/super-admin/_app/settings': typeof SuperAdminAppSettingsRoute
  '/super-admin/_app/storage': typeof SuperAdminAppStorageRoute
  '/super-admin/_app/subscriptions': typeof SuperAdminAppSubscriptionsRoute
  '/super-admin/_app/support': typeof SuperAdminAppSupportRoute
  '/super-admin/_app/system-health': typeof SuperAdminAppSystemHealthRoute
  '/super-admin/_app/tenants': typeof SuperAdminAppTenantsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/super-admin/_app/': typeof SuperAdminAppIndexRoute
  '/_authenticated/app/automotive/customers': typeof AuthenticatedAppAutomotiveCustomersRoute
  '/_authenticated/app/automotive/reports': typeof AuthenticatedAppAutomotiveReportsRoute
  '/_authenticated/app/automotive/reservations': typeof AuthenticatedAppAutomotiveReservationsRoute
  '/_authenticated/app/automotive/sales': typeof AuthenticatedAppAutomotiveSalesRoute
  '/_authenticated/app/automotive/vehicles': typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  '/_authenticated/app/automotive/': typeof AuthenticatedAppAutomotiveIndexRoute
  '/_authenticated/app/automotive/vehicles/$id': typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/register'
    | '/super-admin'
    | '/app'
    | '/super-admin/login'
    | '/app/activity'
    | '/app/billing'
    | '/app/business'
    | '/app/modules'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/team'
    | '/super-admin/access'
    | '/super-admin/announcements'
    | '/super-admin/audit-logs'
    | '/super-admin/brief'
    | '/super-admin/database'
    | '/super-admin/employees'
    | '/super-admin/feature-flags'
    | '/super-admin/notifications'
    | '/super-admin/payments'
    | '/super-admin/profile'
    | '/super-admin/revenue'
    | '/super-admin/settings'
    | '/super-admin/storage'
    | '/super-admin/subscriptions'
    | '/super-admin/support'
    | '/super-admin/system-health'
    | '/super-admin/tenants'
    | '/app/'
    | '/super-admin/'
    | '/app/automotive/customers'
    | '/app/automotive/reports'
    | '/app/automotive/reservations'
    | '/app/automotive/sales'
    | '/app/automotive/vehicles'
    | '/app/automotive/'
    | '/app/automotive/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/register'
    | '/super-admin'
    | '/super-admin/login'
    | '/app/activity'
    | '/app/billing'
    | '/app/business'
    | '/app/modules'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/team'
    | '/super-admin/access'
    | '/super-admin/announcements'
    | '/super-admin/audit-logs'
    | '/super-admin/brief'
    | '/super-admin/database'
    | '/super-admin/employees'
    | '/super-admin/feature-flags'
    | '/super-admin/notifications'
    | '/super-admin/payments'
    | '/super-admin/profile'
    | '/super-admin/revenue'
    | '/super-admin/settings'
    | '/super-admin/storage'
    | '/super-admin/subscriptions'
    | '/super-admin/support'
    | '/super-admin/system-health'
    | '/super-admin/tenants'
    | '/app'
    | '/app/automotive/customers'
    | '/app/automotive/reports'
    | '/app/automotive/reservations'
    | '/app/automotive/sales'
    | '/app/automotive/vehicles'
    | '/app/automotive'
    | '/app/automotive/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/login'
    | '/register'
    | '/super-admin'
    | '/_authenticated/app'
    | '/super-admin/_app'
    | '/super-admin/login'
    | '/_authenticated/app/activity'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/business'
    | '/_authenticated/app/modules'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/team'
    | '/super-admin/_app/access'
    | '/super-admin/_app/announcements'
    | '/super-admin/_app/audit-logs'
    | '/super-admin/_app/brief'
    | '/super-admin/_app/database'
    | '/super-admin/_app/employees'
    | '/super-admin/_app/feature-flags'
    | '/super-admin/_app/notifications'
    | '/super-admin/_app/payments'
    | '/super-admin/_app/profile'
    | '/super-admin/_app/revenue'
    | '/super-admin/_app/settings'
    | '/super-admin/_app/storage'
    | '/super-admin/_app/subscriptions'
    | '/super-admin/_app/support'
    | '/super-admin/_app/system-health'
    | '/super-admin/_app/tenants'
    | '/_authenticated/app/'
    | '/super-admin/_app/'
    | '/_authenticated/app/automotive/customers'
    | '/_authenticated/app/automotive/reports'
    | '/_authenticated/app/automotive/reservations'
    | '/_authenticated/app/automotive/sales'
    | '/_authenticated/app/automotive/vehicles'
    | '/_authenticated/app/automotive/'
    | '/_authenticated/app/automotive/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/super-admin/_app': {
      id: '/super-admin/_app'
      path: ''
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminAppRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activity': {
      id: '/_authenticated/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/business': {
      id: '/_authenticated/app/business'
      path: '/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AuthenticatedAppBusinessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/modules': {
      id: '/_authenticated/app/modules'
      path: '/modules'
      fullPath: '/app/modules'
      preLoaderRoute: typeof AuthenticatedAppModulesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/super-admin/_app/': {
      id: '/super-admin/_app/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminAppIndexRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/access': {
      id: '/super-admin/_app/access'
      path: '/access'
      fullPath: '/super-admin/access'
      preLoaderRoute: typeof SuperAdminAppAccessRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/announcements': {
      id: '/super-admin/_app/announcements'
      path: '/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof SuperAdminAppAnnouncementsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/audit-logs': {
      id: '/super-admin/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof SuperAdminAppAuditLogsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/brief': {
      id: '/super-admin/_app/brief'
      path: '/brief'
      fullPath: '/super-admin/brief'
      preLoaderRoute: typeof SuperAdminAppBriefRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/database': {
      id: '/super-admin/_app/database'
      path: '/database'
      fullPath: '/super-admin/database'
      preLoaderRoute: typeof SuperAdminAppDatabaseRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/employees': {
      id: '/super-admin/_app/employees'
      path: '/employees'
      fullPath: '/super-admin/employees'
      preLoaderRoute: typeof SuperAdminAppEmployeesRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/feature-flags': {
      id: '/super-admin/_app/feature-flags'
      path: '/feature-flags'
      fullPath: '/super-admin/feature-flags'
      preLoaderRoute: typeof SuperAdminAppFeatureFlagsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/notifications': {
      id: '/super-admin/_app/notifications'
      path: '/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof SuperAdminAppNotificationsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/payments': {
      id: '/super-admin/_app/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminAppPaymentsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/profile': {
      id: '/super-admin/_app/profile'
      path: '/profile'
      fullPath: '/super-admin/profile'
      preLoaderRoute: typeof SuperAdminAppProfileRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/revenue': {
      id: '/super-admin/_app/revenue'
      path: '/revenue'
      fullPath: '/super-admin/revenue'
      preLoaderRoute: typeof SuperAdminAppRevenueRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/settings': {
      id: '/super-admin/_app/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminAppSettingsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/storage': {
      id: '/super-admin/_app/storage'
      path: '/storage'
      fullPath: '/super-admin/storage'
      preLoaderRoute: typeof SuperAdminAppStorageRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/subscriptions': {
      id: '/super-admin/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof SuperAdminAppSubscriptionsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/support': {
      id: '/super-admin/_app/support'
      path: '/support'
      fullPath: '/super-admin/support'
      preLoaderRoute: typeof SuperAdminAppSupportRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/system-health': {
      id: '/super-admin/_app/system-health'
      path: '/system-health'
      fullPath: '/super-admin/system-health'
      preLoaderRoute: typeof SuperAdminAppSystemHealthRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/super-admin/_app/tenants': {
      id: '/super-admin/_app/tenants'
      path: '/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof SuperAdminAppTenantsRouteImport
      parentRoute: typeof SuperAdminAppRoute
    }
    '/_authenticated/app/automotive/': {
      id: '/_authenticated/app/automotive/'
      path: '/automotive'
      fullPath: '/app/automotive/'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/customers': {
      id: '/_authenticated/app/automotive/customers'
      path: '/automotive/customers'
      fullPath: '/app/automotive/customers'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/reports': {
      id: '/_authenticated/app/automotive/reports'
      path: '/automotive/reports'
      fullPath: '/app/automotive/reports'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/reservations': {
      id: '/_authenticated/app/automotive/reservations'
      path: '/automotive/reservations'
      fullPath: '/app/automotive/reservations'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveReservationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/sales': {
      id: '/_authenticated/app/automotive/sales'
      path: '/automotive/sales'
      fullPath: '/app/automotive/sales'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/vehicles': {
      id: '/_authenticated/app/automotive/vehicles'
      path: '/automotive/vehicles'
      fullPath: '/app/automotive/vehicles'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveVehiclesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automotive/vehicles/$id': {
      id: '/_authenticated/app/automotive/vehicles/$id'
      path: '/$id'
      fullPath: '/app/automotive/vehicles/$id'
      preLoaderRoute: typeof AuthenticatedAppAutomotiveVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedAppAutomotiveVehiclesRoute
    }
  }
}

interface AuthenticatedAppAutomotiveVehiclesRouteChildren {
  AuthenticatedAppAutomotiveVehiclesIdRoute: typeof AuthenticatedAppAutomotiveVehiclesIdRoute
}

const AuthenticatedAppAutomotiveVehiclesRouteChildren: AuthenticatedAppAutomotiveVehiclesRouteChildren =
  {
    AuthenticatedAppAutomotiveVehiclesIdRoute:
      AuthenticatedAppAutomotiveVehiclesIdRoute,
  }

const AuthenticatedAppAutomotiveVehiclesRouteWithChildren =
  AuthenticatedAppAutomotiveVehiclesRoute._addFileChildren(
    AuthenticatedAppAutomotiveVehiclesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppBusinessRoute: typeof AuthenticatedAppBusinessRoute
  AuthenticatedAppModulesRoute: typeof AuthenticatedAppModulesRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAutomotiveCustomersRoute: typeof AuthenticatedAppAutomotiveCustomersRoute
  AuthenticatedAppAutomotiveReportsRoute: typeof AuthenticatedAppAutomotiveReportsRoute
  AuthenticatedAppAutomotiveReservationsRoute: typeof AuthenticatedAppAutomotiveReservationsRoute
  AuthenticatedAppAutomotiveSalesRoute: typeof AuthenticatedAppAutomotiveSalesRoute
  AuthenticatedAppAutomotiveVehiclesRoute: typeof AuthenticatedAppAutomotiveVehiclesRouteWithChildren
  AuthenticatedAppAutomotiveIndexRoute: typeof AuthenticatedAppAutomotiveIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppBusinessRoute: AuthenticatedAppBusinessRoute,
  AuthenticatedAppModulesRoute: AuthenticatedAppModulesRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAutomotiveCustomersRoute:
    AuthenticatedAppAutomotiveCustomersRoute,
  AuthenticatedAppAutomotiveReportsRoute:
    AuthenticatedAppAutomotiveReportsRoute,
  AuthenticatedAppAutomotiveReservationsRoute:
    AuthenticatedAppAutomotiveReservationsRoute,
  AuthenticatedAppAutomotiveSalesRoute: AuthenticatedAppAutomotiveSalesRoute,
  AuthenticatedAppAutomotiveVehiclesRoute:
    AuthenticatedAppAutomotiveVehiclesRouteWithChildren,
  AuthenticatedAppAutomotiveIndexRoute: AuthenticatedAppAutomotiveIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SuperAdminAppRouteChildren {
  SuperAdminAppAccessRoute: typeof SuperAdminAppAccessRoute
  SuperAdminAppAnnouncementsRoute: typeof SuperAdminAppAnnouncementsRoute
  SuperAdminAppAuditLogsRoute: typeof SuperAdminAppAuditLogsRoute
  SuperAdminAppBriefRoute: typeof SuperAdminAppBriefRoute
  SuperAdminAppDatabaseRoute: typeof SuperAdminAppDatabaseRoute
  SuperAdminAppEmployeesRoute: typeof SuperAdminAppEmployeesRoute
  SuperAdminAppFeatureFlagsRoute: typeof SuperAdminAppFeatureFlagsRoute
  SuperAdminAppNotificationsRoute: typeof SuperAdminAppNotificationsRoute
  SuperAdminAppPaymentsRoute: typeof SuperAdminAppPaymentsRoute
  SuperAdminAppProfileRoute: typeof SuperAdminAppProfileRoute
  SuperAdminAppRevenueRoute: typeof SuperAdminAppRevenueRoute
  SuperAdminAppSettingsRoute: typeof SuperAdminAppSettingsRoute
  SuperAdminAppStorageRoute: typeof SuperAdminAppStorageRoute
  SuperAdminAppSubscriptionsRoute: typeof SuperAdminAppSubscriptionsRoute
  SuperAdminAppSupportRoute: typeof SuperAdminAppSupportRoute
  SuperAdminAppSystemHealthRoute: typeof SuperAdminAppSystemHealthRoute
  SuperAdminAppTenantsRoute: typeof SuperAdminAppTenantsRoute
  SuperAdminAppIndexRoute: typeof SuperAdminAppIndexRoute
}

const SuperAdminAppRouteChildren: SuperAdminAppRouteChildren = {
  SuperAdminAppAccessRoute: SuperAdminAppAccessRoute,
  SuperAdminAppAnnouncementsRoute: SuperAdminAppAnnouncementsRoute,
  SuperAdminAppAuditLogsRoute: SuperAdminAppAuditLogsRoute,
  SuperAdminAppBriefRoute: SuperAdminAppBriefRoute,
  SuperAdminAppDatabaseRoute: SuperAdminAppDatabaseRoute,
  SuperAdminAppEmployeesRoute: SuperAdminAppEmployeesRoute,
  SuperAdminAppFeatureFlagsRoute: SuperAdminAppFeatureFlagsRoute,
  SuperAdminAppNotificationsRoute: SuperAdminAppNotificationsRoute,
  SuperAdminAppPaymentsRoute: SuperAdminAppPaymentsRoute,
  SuperAdminAppProfileRoute: SuperAdminAppProfileRoute,
  SuperAdminAppRevenueRoute: SuperAdminAppRevenueRoute,
  SuperAdminAppSettingsRoute: SuperAdminAppSettingsRoute,
  SuperAdminAppStorageRoute: SuperAdminAppStorageRoute,
  SuperAdminAppSubscriptionsRoute: SuperAdminAppSubscriptionsRoute,
  SuperAdminAppSupportRoute: SuperAdminAppSupportRoute,
  SuperAdminAppSystemHealthRoute: SuperAdminAppSystemHealthRoute,
  SuperAdminAppTenantsRoute: SuperAdminAppTenantsRoute,
  SuperAdminAppIndexRoute: SuperAdminAppIndexRoute,
}

const SuperAdminAppRouteWithChildren = SuperAdminAppRoute._addFileChildren(
  SuperAdminAppRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminAppRoute: typeof SuperAdminAppRouteWithChildren
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAppRoute: SuperAdminAppRouteWithChildren,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
